### PR TITLE
Better plugin behaviour

### PR DESCRIPTION
**Pull request by evildmp**
And a start on some fuller documentation.

Are you happy to hook these docs into RTFD?

### CODE REVIEW

**Comment by evildmp** [comment]
Also added, easy and backwards-compatible control over headings in templates.

**Comment by romlok** [comment]
Yes, I'm more than happy to have documentation in RTFD!
However, I'm not over-the-moon about so many unrelated things appearing in a single pull request - especially when I'm willing to pull only some of the commits, without further discussion. Can you split these into separate pull requests?
I'll comment more specifically in the changesets themselves. :)

**Comment by evildmp** [comment]
I take your point about separating all these out into separate commits, but I am not sure where to start, especially since many of them depend on others.

**Comment by romlok** [comment]
I wasn't actually so concerned with separating the changes into multiple commits, as separating the commits into multiple pull requests! But then I remembered I could just cherry-pick the simple commits, so I have done so for: the start of docs, and template syntax fix. 
If you can see to rebase this branch (to eliminate the commit dupes), and accommodate my suggestions (especially the problem of backward-incompatibility), I'd be happy to merge in your improvements. I'm closing this pull request, but please open a new one when you're ready. :)

**Pull request closed without merging**
